-- MySQL Script generated by MySQL Workbench
-- 08/25/16 20:41:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vacina
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vacina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vacina` DEFAULT CHARACTER SET utf8 ;
USE `vacina` ;

-- -----------------------------------------------------
-- Table `vacina`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacina`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id que representa a conta do usuario, este numero é unico',
  `usuario` VARCHAR(45) NOT NULL COMMENT 'nome de usuario, deve ser unico',
  `senha` VARCHAR(32) NOT NULL COMMENT 'senha para realizar o login',
  `tipo` TINYINT(1) NOT NULL COMMENT 'identifica se a conta pertence a um posto de saude, agente de saude ou cidadão',
  `perm` TINYINT(1) NOT NULL COMMENT 'representa o nivel de permissão da conta, variando de 0 a 3, 0 admin, 1 posto de saude, 2 agente de saude e 3 usuario',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vacina`.`cidadao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacina`.`cidadao` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id da informação para controle da tabela',
  `id_usuario` INT NOT NULL COMMENT 'id do usuario a quem esta informação pertence',
  `nome` VARCHAR(60) NOT NULL COMMENT 'nome completo do usuario',
  `cep` VARCHAR(9) NOT NULL COMMENT 'CEP do usuario',
  `estado` CHAR(2) NOT NULL COMMENT 'id do estado em que o usuario reside',
  `cidade` VARCHAR(60) NOT NULL COMMENT 'id da cidade na qual o usuario reside',
  `bairro` VARCHAR(45) NOT NULL COMMENT 'bairro onde o usuario reside',
  `rua` VARCHAR(60) NOT NULL COMMENT 'nome da rua onde o usuario reside',
  `numero` INT NULL COMMENT 'numero da cada onde o usuario reside',
  `complemento` VARCHAR(20) NULL COMMENT 'informações adicionais para o endereço',
  `telefone` VARCHAR(15) NULL COMMENT 'telefone para contato',
  `cpf` VARCHAR(14) NULL COMMENT 'cpf do usuario',
  `nome_mae` VARCHAR(60) NULL COMMENT 'nome da mãe do usuario',
  `nome_pai` VARCHAR(60) NULL,
  `data_nasc` DATE NULL COMMENT 'data de nascimento do usuario',
  `num_sus` VARCHAR(15) NULL COMMENT 'numero da carteirinha do SUS do usuario',
  `reg_nasc` VARCHAR(32) NULL COMMENT 'numero da certidao de nascimento',
  `local_nasc` VARCHAR(60) NULL COMMENT 'local de nascimento',
  `estado_nasc` CHAR(2) NOT NULL COMMENT 'id do estado em que o usuario nasceu',
  `cidade_nasc` VARCHAR(60) NOT NULL,
  `sexo` CHAR(1) NOT NULL COMMENT 'sexo do usuario',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vacina`.`vacina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacina`.`vacina` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id da vacina',
  `nome` VARCHAR(60) NOT NULL COMMENT 'nome da vacina',
  `doses` INT NOT NULL COMMENT 'numero de doses necessárias',
  `intervalo` INT NOT NULL COMMENT 'intervalo entre as doses em meses',
  `obrigatorio` TINYINT(1) NOT NULL COMMENT 'flag para informar se a vacina é obrigatoria ou não',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vacina`.`agente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacina`.`agente` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id da informação',
  `id_usuario` INT NOT NULL COMMENT 'id do usuario a qual a informação eprtence',
  `nome` VARCHAR(60) NOT NULL COMMENT 'nome completo do agente ou posto de saude',
  `estado` CHAR(2) NOT NULL COMMENT 'estado de atuação do agente/posto de saude',
  `cidade` VARCHAR(60) NOT NULL COMMENT 'id da cidade de atuação do agente/posto de saude',
  `cpf` VARCHAR(12) NOT NULL,
  `id_posto_vinculado` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_cnpj_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vacina`.`posto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacina`.`posto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `telefone` CHAR(11) NULL,
  `cep` CHAR(8) NULL,
  `cidade` VARCHAR(60) NULL,
  `estado` CHAR(2) NULL,
  `bairro` VARCHAR(60) NULL,
  `rua` VARCHAR(60) NULL,
  `numero` INT NULL,
  `complemento` VARCHAR(20) NULL,
  `cnpj` CHAR(15) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC),
  UNIQUE INDEX `cidade_UNIQUE` (`cidade` ASC),
  UNIQUE INDEX `estado_UNIQUE` (`estado` ASC),
  UNIQUE INDEX `bairro_UNIQUE` (`bairro` ASC),
  UNIQUE INDEX `rua_UNIQUE` (`rua` ASC),
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vacina`.`cidadao_vacina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacina`.`cidadao_vacina` (
  `id_usuario` INT NOT NULL COMMENT 'id a quem o registro pertence',
  `id_vacina` INT NOT NULL COMMENT 'identificação da vacina',
  `dose` INT NOT NULL COMMENT 'dose de aplicação',
  `data` DATE NOT NULL COMMENT 'data da aplicação',
  `id_posto` INT NULL COMMENT 'id do local onde a vacina foi aplicada',
  `id_agente` INT NULL COMMENT 'id do agente que realizou a aplicação')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
